// import { PDFDocument, rgb } from "react-native-pdf-lib";

// export const generatePDF = async (resumeData) => {
//   const {
//     personalDetails,
//     experienceDetails,
//     projectDetails,
//     educationDetails,
//     certificationDetails,
//   } = resumeData;

//   try {
//     const pdfDoc = await PDFDocument.create();
//     const page = pdfDoc.addPage([600, 800]);

//     let y = page.getHeight() - 50;

//     const addText = (text) => {
//       y -= 20;
//       page.drawText(text, {
//         x: 50,
//         y,
//         size: 12,
//         color: rgb(0, 0, 0),
//       });
//     };

//     addText("Resume Preview");
//     addText(" ");

//     addText("Personal Details:");
//     addText(`Name: ${personalDetails.name}`);
//     addText(`Email: ${personalDetails.email}`);
//     addText(" ");

//     addText("Experience:");
//     experienceDetails.forEach((experience) => {
//       addText(`Company: ${experience.company}`);
//       addText(`Position: ${experience.position}`);
//       addText(" ");
//     });

//     addText("Projects:");
//     projectDetails.forEach((project) => {
//       addText(`Project Name: ${project.projectName}`);
//       addText(`Description: ${project.description}`);
//       addText(" ");
//     });

//     addText("Education:");
//     educationDetails.forEach((education) => {
//       addText(`School: ${education.school}`);
//       addText(`Degree: ${education.degree}`);
//       addText(" ");
//     });

//     addText("Certifications:");
//     certificationDetails.forEach((certification) => {
//       addText(`Certification Name: ${certification.certificationName}`);
//       addText(`Issued By: ${certification.issuedBy}`);
//       addText(" ");
//     });

//     page.drawRectangle({
//       x: 50,
//       y: page.getHeight() - 50,
//       width: 500,
//       height: 2,
//       color: rgb(0, 0, 0),
//     });

//     page.drawText("Generated by Your App", {
//       x: 50,
//       y: page.getHeight() - 80,
//       size: 10,
//       color: rgb(0, 0, 0),
//     });

//     const pdfBytes = await pdfDoc.save();

//     return pdfBytes;
//   } catch (error) {
//     console.error("Error generating PDF:", error);
//     throw error; // Rethrow the error to handle it in the calling function
//   }
// };
import RNHTMLtoPDF from "react-native-html-to-pdf";

//RNHTMLtoPDF.createPDFService();
const generatePDF = async (resumeData) => {
  const {
    personalDetails,
    experienceDetails,
    projectDetails,
    educationDetails,
    certificationDetails,
  } = resumeData;

  const htmlContent = `
    <h1>Resume Preview</h1>
    <h2>Personal Details:</h2>
    <p>Name: ${personalDetails.name}</p>
    <p>Email: ${personalDetails.email}</p>

    <h2>Experience:</h2>
    ${experienceDetails
      .map(
        (experience) => `
      <p>Company: ${experience.company}</p>
      <p>Position: ${experience.position}</p>
    `
      )
      .join("")}

    <h2>Projects:</h2>
    ${projectDetails
      .map(
        (project) => `
      <p>Project Name: ${project.projectName}</p>
      <p>Description: ${project.description}</p>
    `
      )
      .join("")}

    <h2>Education:</h2>
    ${educationDetails
      .map(
        (education) => `
      <p>School: ${education.school}</p>
      <p>Degree: ${education.degree}</p>
    `
      )
      .join("")}

    <h2>Certifications:</h2>
    ${certificationDetails
      .map(
        (certification) => `
      <p>Certification Name: ${certification.certificationName}</p>
      <p>Issued By: ${certification.issuedBy}</p>
    `
      )
      .join("")}
  `;

  const options = {
    html: `<html><body>${htmlContent}</body></html>`,
    fileName: "resume",
    directory: "Documents",
  };

  try {
    const pdf = await RNHTMLtoPDF.convert(options);
    return pdf.filePath;
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw error;
  }
};

export default generatePDF;
